[2022-10-25 15:21:20,775] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-10-25T15:21:17.286646+00:00 [queued]>
[2022-10-25 15:21:20,797] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-10-25T15:21:17.286646+00:00 [queued]>
[2022-10-25 15:21:20,798] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-25 15:21:20,799] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-25 15:21:20,800] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-25 15:21:20,855] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-10-25 15:21:17.286646+00:00
[2022-10-25 15:21:20,864] {standard_task_runner.py:52} INFO - Started process 943 to run task
[2022-10-25 15:21:20,874] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-10-25T15:21:17.286646+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpoabknnss', '--error-file', '/tmp/tmpa1b3tjqv']
[2022-10-25 15:21:20,876] {standard_task_runner.py:80} INFO - Job 153: Subtask load_seed_data_once
[2022-10-25 15:21:21,045] {task_command.py:369} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-10-25T15:21:17.286646+00:00 [running]> on host 0508f368e846
[2022-10-25 15:21:21,883] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-10-25T15:21:17.286646+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-25T15:21:17.286646+00:00
[2022-10-25 15:21:21,912] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-25 15:21:21,946] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-10-25 15:21:22,005] {subprocess.py:85} INFO - Output:
[2022-10-25 15:21:33,155] {subprocess.py:92} INFO - [0m15:21:33  Encountered an error:
[2022-10-25 15:21:33,156] {subprocess.py:92} INFO - Runtime Error
[2022-10-25 15:21:33,156] {subprocess.py:92} INFO -   fatal: Not a dbt project (or any of the parent directories). Missing dbt_project.yml file
[2022-10-25 15:21:33,376] {subprocess.py:96} INFO - Command exited with return code 2
[2022-10-25 15:21:33,425] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-25 15:21:33,434] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20221025T152117, start_date=20221025T152120, end_date=20221025T152133
[2022-10-25 15:21:33,473] {standard_task_runner.py:97} ERROR - Failed to execute job 153 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 2.; 943)
[2022-10-25 15:21:33,494] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-25 15:21:33,599] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
