[2022-10-25 15:19:34,747] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-10-25T15:19:32.224186+00:00 [queued]>
[2022-10-25 15:19:34,812] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-10-25T15:19:32.224186+00:00 [queued]>
[2022-10-25 15:19:34,820] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-25 15:19:34,833] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-25 15:19:34,834] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-25 15:19:34,962] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-10-25 15:19:32.224186+00:00
[2022-10-25 15:19:34,983] {standard_task_runner.py:52} INFO - Started process 865 to run task
[2022-10-25 15:19:35,003] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-10-25T15:19:32.224186+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpl65bs49y', '--error-file', '/tmp/tmp_e3m7ddm']
[2022-10-25 15:19:35,034] {standard_task_runner.py:80} INFO - Job 152: Subtask load_seed_data_once
[2022-10-25 15:19:35,593] {task_command.py:369} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-10-25T15:19:32.224186+00:00 [running]> on host 0508f368e846
[2022-10-25 15:19:36,752] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-10-25T15:19:32.224186+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-25T15:19:32.224186+00:00
[2022-10-25 15:19:36,759] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-25 15:19:36,765] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt_project && dbt seed --profiles-dir .']
[2022-10-25 15:19:36,806] {subprocess.py:85} INFO - Output:
[2022-10-25 15:19:36,819] {subprocess.py:92} INFO - bash: line 1: cd: /dbt_project: No such file or directory
[2022-10-25 15:19:36,831] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-25 15:19:36,966] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-25 15:19:36,995] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20221025T151932, start_date=20221025T151934, end_date=20221025T151936
[2022-10-25 15:19:37,132] {standard_task_runner.py:97} ERROR - Failed to execute job 152 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 1.; 865)
[2022-10-25 15:19:37,187] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-25 15:19:37,507] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
